import Layout from 'components/layout/Layout';
import Blobs from 'components/ui/Blobs';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>elCode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body></body>
    </div>
  );
};

export default Home;
