import Layout from 'components/layout/Layout';
import Blobs from 'components/ui/Blobs';
import type { NextPage } from 'next';
import Head from 'next/head';
import Dashboard from './Dashboard';
import { CustomNextPage } from 'types';

const Home: CustomNextPage = () => {
  return (
    <div>
      <Head>
        <title>elCode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body></body>
    </div>
  );
};

export default Home;

// Home.Layout = (Page: any) => <Layout>{Page}</Layout>;
